### ISSUE TITLE
Непонятный баг в фикстурах

### ISSUE THREAD

**Issue by alexicon33** [HobbyTaste/backend#9]
Возможно, я столкнулся с неким асинхронным багом при загрузке фикстур, возникающим при запуска скрипта `start-db` или при запуске очередной группы тестов.  
### Ожидаемое поведение
База данных успешно разворачивается, фикстуры в неё успешно загружаются, после чего скрипт завершается c кодом возврата 0.
### Реальное поведение
База данных успешно разворачивается, после чего скрипт выдаёт ошибку `Unhandled rejection TypeError: Cannot read property '_id' of undefined` и зависает.
### Лог выполнения
Вот простой пример: https://pastebin.com/x0uTziNG
Вот пример, когда это вылетает прямо во время тестирования: https://pastebin.com/BFSHvTBt
### Как воспроизвести?
Позапускать много раз скрипт `start-db` (см. ветку master). При этом баг проявляется не так уж и редко, примерно раз из десяти запусков. Можно позапускать много раз команду `yarn test`: так придётся дольше ждать, но можно будет видеть ситуации в духе второго примера. Баг тоже проявляется где-то в 10% запусков.
### Мысли по этому поводу
В логах видно, что всё нарушается в 24 строчке файла `hobbies_.js`, где мы не можем прочитать `_id` партнёра, поскольку этот партнёр вдруг оказывается `undefined`. Т.е., мы почему-то не можем его найти в списке. Почему это так, и почему в большинстве случаев всё проходит хорошо, что говорит о том, что ошибка _не_ в данных, я пока не понимаю. 
Учитывая характер возникающей ошибки (появляется произвольно где-то в 10% одинаковых и независимых запусков), могу предположить, что где-то что-то нарушается в асинхронных операциях.

**Comment by alexicon33** [comment]
Немного поигрался с этим. Мне кажется следующее:
Исходники `node-mongodb-fixtures` говорят, что все скрипты постобработки данных запускаются "параллельно" (там стоит Promise.all, см. [реализацию](https://github.com/cdimascio/node-mongodb-fixtures/blob/40ae7c91b0c10f1fed2ce37dbda0bc1df100887a/lib/index.js#L118)). 
Поэтому происходит что-то подобное:
1. Скрипт `hobbies_.js` доходит до 19 строчки, успешно получает список хобби и пользователей, но не успевает забрать также и провайдеров.
2. Затем скрипт `providers_.js` доходит до 10 строчки (c deleteMany), удаляет провайдеров из базы, но не успевает добавить изменённые данные.
3. Скрипт `hobbies_.js` просыпается, получает список провайдеров из базы. Однако он оказывается пустым, из-за чего мы дальше (в 23 строчке) не можем найти hobbyOwner'а, и он оказывается undefined.  

Хочется как-то упорядочить запуск скриптов, чтобы такого не возинкало. Например, сначала просто загружая все данные из json'ов, а потом запуская цепочку промисов из скриптов постобработки. Похоже, даже, что так не очень много придётся переписывать.

**Comment by alexicon33** [comment]
@SNVC1, воспроизводится ли баг? Не пишу ли я чушь? Просто странно, что я раньше с ним не сталкивался.

**Comment by SNVC1** [comment]
@alexicon33, странно, у меня баг не воспроизводится, но кажется, что описанный тобой сценарий действительно может иметь место. В любом случае, спасибо за все подробности, с меня фикс в ближайшем будущем

**Comment by makut** [comment]
Тоже с этим сталкивался, причем на разных версиях репозитория
